<span style="font-size:30px">**Preprocesado de datos.**</span> 
    
<span style="font-family: 'Verdana'; color: red;"> *Bronquivoide* </span>

### Vamos a realizar una serie de ejercicios que conforman el procedimiento de preprocesado de datos. Lo haremos desde el punto de vista de la teoría del aprendizaje supervisado. 

### Usaremos un archivo de formato CSV (Comma-Separated Values) de nombre *Datos_Preprocesado.csv*

# **EJERCICIOS:**

### **1) Cargar, leer y mostrar los datos del archivo (como es un arreglo de orden $10 \times 4$ se puede visualizar completamente, en formato RENGLONES $\times$ COLUMNAS).**

### **2) Generar un arreglo, digamos $X$, que muestre los valores asociados a las entradas de las primeras tres columnas.** 

### Es decir, si vemos cada columna de nuestro conjunto de datos como un vector columna ($\{\vec{v_1},\vec{v_2},\vec{v_3},\vec{v_4}\}$); lo que haremos será tomar una matriz que concatena los primeros tres vectores columna: $X=[\vec{v_1},\vec{v_2},\vec{v_3}]$

### **3) Trabajando con los datos de $X$, operar los datos faltantes (NaN) de las columnas 2 y 3 sustituyéndolos por el valor del promedio asociado a cada columna.** 

### Nota: Como las columnas 1 y 4 tienen valores representados por datos categóricos, para este inciso tomemos únicamente las columnas 2 y 3.

### **4) Codificar los datos categóricos de la primera columna de $X$. Es decir, transformar las entradas con categorías a valores numéricos.**

### **5) Transformar los valores ordinales resultado de la codificación de los datos categóricos a variables *dummy*.**

In [27]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

#Ejercicio 1
print(f"Ejercicio 1:")
print( "\n")
#Carga y lectura de datos mediante la biblioteca Pandas:
datos=pd.read_csv('Datos_Preprocesado.csv')
print(f"Los datos del archivo CSV son: \n")
display(datos)
print( "\n")

#Ejercicio 2
print(f"Ejercicio 2:")
print( "\n")
#Arreglo de Python (o matriz) que muestra únicamente los valores en las primeras tres columnas:
X=datos.iloc[:,:-1].values
print(f"El arreglo de valores, X, es: \n \n {X}")
print( "\n")

#Ejercicio 3
print(f"Ejercicio 3:")
print( "\n")
#Definimos el método especificado en el ejercicio para operar los NaN:
método=SimpleImputer(missing_values=np.nan, strategy="mean")
#Aplicamos el método únicamente sobre las columnas 2 y 3:
ajuste=método.fit(X[:,1:3]) 
#Sobreescribir los datos con este ajuste:
X[:,1:3]=ajuste.transform(X[:,1:3])
#Mostrar el nuevo arreglo de datos:
print(f"El nuevo arreglo X con el procedimiento de valores faltantes especificado es: \n \n {X}")
print( "\n")

#Ejercicio 4
print(f"Ejercicio 4:")
print( "\n")
codificación=LabelEncoder() #Creamos el codificador
X[:,0]=codificación.fit_transform(X[:,0])
print(f"El arreglo con los datos categóricos codificados es: \n \n {X}")
print( "\n")

#Ejercicio 5
print(f"Ejercicio 5:")
print( "\n")
tranformación_columnas=ColumnTransformer([('dummys', OneHotEncoder(categories='auto'), [0])], remainder='passthrough')
X = np.array(tranformación_columnas.fit_transform(X))
print(f"El arreglo con las variables dummy es: \n \n {X}")
print( "\n")

Ejercicio 1:


Los datos del archivo CSV son: 



Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes



Ejercicio 2:


El arreglo de valores, X, es: 
 
 [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Ejercicio 3:


El nuevo arreglo X con el procedimiento de valores faltantes especificado es: 
 
 [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Ejercicio 4:


El arreglo con los datos categóricos codificados es: 
 
 [[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


Ejercicio 5:


El arreglo con las variables dummy 

### Nótense las formas de los mapeos que hemos hecho en la primera columna. Primero mapeamos las entradas del vector $\vec{v_1}$ de dimensión $10$, las cuales eran cadenas de caracteres, a valores numéricos ordinales, esto corresponde al proceso de codificación. Podemos verlo de la siguiente forma:

### $ CODIFICACIÓN: CARACTERES \rightarrow \mathbb{R}$, mediante $CODIFICACIÓN(v_1 ^ m)=a$. En donde en este caso $a\in \{0,1,2\}$ (el término $ v_1 ^ m$ hace referencia a la $m$-ésima entrada de $\vec{v_1}$).

### Luego implementamos un mapeo que podemos ver de la forma:

### $ DUMMY: CARACTERES \rightarrow \{0,1\}$, mediante $DUMMY(v_1 ^ m)=0,1$

### Lo anterior de tal forma que la matriz $X$ de tres columnas pasó a ser de cinco columnas ($X=[\vec{v_1},\vec{v_2},\vec{v_3},\vec{v_4},\vec{v_5}]$), pues la transformación de valores ordinales a no ordinales (dummy) resultó en una clasificación binaria de tres datos categóricos posibles ("France", "Spain" y "Germany")

### **6) Dividir el data set en conjunto de entrenamiento y conjunto de prueba.**

### Recordemos que el conjunto de entrenamiento está definido por el conjunto de pares $\{ (\vec{x_i}, y_i)\}_{i=1} ^n$, en donde $\{ \vec{x_i}\}$ es el conjunto de ejemplares de entrada  tal que $ \vec{x_i} \in \mathbb{R}^d$ ($d$ es la dimensión del espacio de entradas), mientras que $\{ y_i\}$ es el conjunto de ejemplares de salida (o predicciones) tal que $y_i \in \mathbb{R}$.

### Consideremos las salidas $y_i$ como los datos de la cuarta columna de Datos_Preprocesado.csv, así, en nuestro caso las entradas $\vec{x_i}$ son los vectores renglones tal que $i=1,2,..,10$. La concatenación vertical de los $\vec{x_i}$ van a conformar la matriz $X$.

### De lo anterior, vamos a tener dos conjuntos de pares:

<font size="5">  $\{ (\vec{x_i}^{train}, y_i ^{train})\}_{i=1} ^{10}$ </font>

<font size="5">  $\{ (\vec{x_i}^{test}, y_i ^{test})\}_{i=1} ^{10}$ </font>

### Nota: Para dividir el data set tendremos que considerar el vector columna $\vec{y}$ de entradas $y_i$ y codificar también sus entradas, pues contiene datos categóricos.

In [31]:
#Ejercicio 6
print(f"Ejercicio 6:")
print( "\n")
#Definimos el vector de salidas y:
y=datos.iloc[:, 3].values
print(f"El vector de salidas, y, es: \n \n {y}")
print( "\n")
#Codificando las categorías:
codificación_y=LabelEncoder()
y=codificación_y.fit_transform(y)
print(f"El vector y codificado es: \n \n {y}")
print( "\n")
#División en datos de train y de test:
X_train , X_test , y_train , y_test = train_test_split(X, y, test_size = 0.2) #El test size de 0.2 manda 20% de datos al testing.
print(f"La matriz X de entrenamiento es: \n \n {X_train}")
print( "\n")
print(f"La matriz X de prueba es: \n \n {X_test}")
print( "\n")
print(f"El vector y de entrenamiento es: \n \n {y_train}")
print( "\n")
print(f"El vector y de prueba es: \n \n {y_test}")
print( "\n")

Ejercicio 6:


El vector de salidas, y, es: 
 
 ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


El vector y codificado es: 
 
 [0 1 0 0 1 1 0 1 0 1]


La matriz X de entrenamiento es: 
 
 [[1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]]


La matriz X de prueba es: 
 
 [[0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]]


El vector y de entrenamiento es: 
 
 [1 1 1 0 0 0 1 0]


El vector y de prueba es: 
 
 [0 1]




### 7) Realizar un escalamiento de datos al conjunto $X$ de entrenamiento y al de prueba.

### Nota: La función StandardScaler() realiza una normalización (o bien, una estandarización) a cada entrada de la matriz $X$ en términos del promedio y la desviación estándar de cada columna:

<font size="5"> $Sc(X_{ij})=\frac{X_{ij}-\mu_j}{\sigma _j}$</font>

In [30]:
#Ejercicio 7
print(f"Ejercicio 7:")
print( "\n")
#Llamamos a la función de escalamiento:
sc_X=StandardScaler()
#Escalamiento para X_train:
X_train=sc_X.fit_transform(X_train)
#Escalamiento para X_test:
X_test=sc_X.transform(X_test)
print(f"El conjunto X de entrenamiento escalado es: \n \n {X_train}")
print( "\n")
print(f"El conjunto X de prueba escalado es: \n \n {X_test}")
print( "\n")

Ejercicio 7:


El conjunto X de entrenamiento escalado es: 
 
 [[ 1.         -0.37796447 -0.77459667  0.61435084  0.59805036]
 [ 1.         -0.37796447 -0.77459667 -0.6781795  -0.59805036]
 [-1.         -0.37796447  1.29099445 -1.82709535 -1.45240802]
 [-1.          2.64575131 -0.77459667  1.47603773  1.53784378]
 [ 1.         -0.37796447 -0.77459667  1.18880877  1.19610072]
 [-1.         -0.37796447  1.29099445 -0.1356359  -1.11066496]
 [-1.         -0.37796447  1.29099445 -0.24733605 -0.34174306]
 [ 1.         -0.37796447 -0.77459667 -0.39095053  0.17087153]]


El conjunto X de prueba escalado es: 
 
 [[-1.          2.64575131 -0.77459667 -1.39625191 -0.93979342]
 [-1.          2.64575131 -0.77459667  0.03989291 -0.10442149]]




# Fin de los ejercicios.